Monoid 初稿
FizzyElt/functional-programming pull request #11
Opened 2023-08-11 15:56 UTC by FizzyElt

2023-08-11 16:09 UTC, dannypsnl requested changes

2023-08-11 16:09 UTC, dannypsnl commented on Monoid.md
> +基於 [Semigroup](./Monoid.md) 上，從集合中找出一個 identity element (這裡記作 $e$) 並且與其他元素滿足一下條件：
Semigroup 連結錯誤

2023-08-11 16:09 UTC, dannypsnl commented on Monoid.md
> +3. $e\ \circ\ a = a = a\ \circ\ e$
二元函數本身並不是規則，而是「語法」

2023-08-11 16:09 UTC, dannypsnl commented on Monoid.md
> +
可以考慮加上有限自動機的 characteristic monoid 作為實際案例

2023-08-11 16:48 UTC, dannypsnl commented
Semigroup 那邊其實我覺得也需要有真的是「剛好」是半群的，而不是拿超過的結構來用

2023-08-12 13:49 UTC, FizzyElt commented
意思是找一個有 Semigroup 但沒有 identity 的實際案例嘛？

2023-08-12 13:54 UTC, dannypsnl commented
是，不過那不完全是此 PR 的內容就是了

2023-08-13 11:59 UTC, FizzyElt commented on Monoid.md
> +3. $e\ \circ\ a = a = a\ \circ\ e$
改成兩條

2023-08-13 12:02 UTC, FizzyElt commented on Monoid.md
> +
自動機部份我什麼接觸，我要研究一下，先開個 issue

2023-08-13 13:43 UTC, dannypsnl commented on Monoid.md
> +3. $e\ \circ\ a = a = a\ \circ\ e$
我覺得可以統一成「等式規則」因為這確實是代數的核心「什麼一樣」

2023-08-13 13:49 UTC, dannypsnl commented on Monoid.md
> +
就是 function compose 是乘法
單元函數是 identity 
全體轉移函數是元素的 monoid

2023-08-14 08:07 UTC, dannypsnl requested changes

2023-08-14 08:07 UTC, dannypsnl commented on Monoid.md
> +所以一個 Monoid $(S,\ \circ,\ e)$ 會有以下兩個規則
「等式規則」

2023-08-14 08:07 UTC, dannypsnl commented on Monoid.md
> +Monoid 恰好是只有一個物件的 [locally small category](./intuitive_category_theory.md)，identity morphism 對應 $e$，而組合兩個 morphism 正好得到另一個 morphism
另一個描述是「有 Hom set」的 category，因為實際上只有 1 個物件的情況下一定是 small category，用 locally small 描述略為尷尬

2023-08-14 14:29 UTC, dannypsnl approved these changes

2023-08-14 15:54 UTC, FizzyElt commented
半自動機有很多符號沒解釋，但感覺偏離主題，先挑重點講

2023-08-14 19:45 UTC, dannypsnl commented
沒關係，反正這裡是介紹 monoid，只是想讓案例裡面有一些有實際用途的東西

2023-08-15 01:18 UTC, merged