data first, data last 初稿
FizzyElt/functional-programming pull request #15
Opened 2023-08-15 15:40 UTC by FizzyElt

2023-08-15 16:13 UTC, dannypsnl requested changes

2023-08-15 16:13 UTC, dannypsnl commented on data_first_and_data_last.md
> +const double = map((num) => num * 2)
你這裡還做了 eta，建議給出 rhs 即可

並且可以增加 `map` 形式程式的層數

2023-08-15 16:13 UTC, dannypsnl commented on data_first_and_data_last.md
> +答案是：沒辦法，因為即便在柯里化的情況下第一個參數就被迫要給資料，並且這樣再做 `compose` 已經沒有太大意義了。
這不是事實，有兩個辦法解決這個問題
1. pipeline 不是 data last 而是為 data first 設計，elixir 就是這樣處理的，所以程式會是

   ```elixir
   [1, 2, 3, 4]
     |> Enum.map(fn x -> x * 2 end)
     |> Enum.map(fn x -> x - 1 end)
   ```
3. 再加一個功能：參數語法糖，令 `_n` 表示第 $n$ 個略參數，這樣還是可以拿出來 compose

2023-08-15 16:13 UTC, dannypsnl commented on data_first_and_data_last.md
> +假設我們的需求是將主流程的資訊接在 `arr` 的前面，但一般作法似乎會有錯誤：
flip 函數？

2023-08-15 16:32 UTC, FizzyElt commented on data_first_and_data_last.md
> +const double = map((num) => num * 2)
eta 跟 rhs 是什麼

2023-08-16 06:44 UTC, FizzyElt commented on data_first_and_data_last.md
> +const double = map((num) => num * 2)
所以我只要寫 `map((num) => num * 2)` 這樣即可
那 map 形式程式的層數指的是什麼？

2023-08-16 06:47 UTC, FizzyElt commented on data_first_and_data_last.md
> +答案是：沒辦法，因為即便在柯里化的情況下第一個參數就被迫要給資料，並且這樣再做 `compose` 已經沒有太大意義了。
第一種在 JS 是不是就是 chaining 的作法 [https://lodash.com/docs/4.17.15#chain](https://lodash.com/docs/4.17.15#chain)

2023-08-16 07:10 UTC, dannypsnl commented on data_first_and_data_last.md
> +答案是：沒辦法，因為即便在柯里化的情況下第一個參數就被迫要給資料，並且這樣再做 `compose` 已經沒有太大意義了。
Yep

2023-08-16 07:11 UTC, dannypsnl commented on data_first_and_data_last.md
> +const double = map((num) => num * 2)
多加幾個 map

2023-08-17 15:47 UTC, dannypsnl commented on data_first_and_data_last.md
> +答案是：沒辦法，因為即便在柯里化的情況下第一個參數就被迫要給資料，並且這樣再做 `compose` 已經沒有太大意義了。
Scala:

```scala
List(1, 2, 3, 4).map(_ * 2) == List(2, 4, 6, 8)
```

2023-08-17 16:10 UTC, FizzyElt commented on data_first_and_data_last.md
> +答案是：沒辦法，因為即便在柯里化的情況下第一個參數就被迫要給資料，並且這樣再做 `compose` 已經沒有太大意義了。
placeholder 是不是算是在模擬這種語法糖？

2023-08-17 16:36 UTC, dannypsnl commented on data_first_and_data_last.md
> +答案是：沒辦法，因為即便在柯里化的情況下第一個參數就被迫要給資料，並且這樣再做 `compose` 已經沒有太大意義了。
是

2023-08-17 22:01 UTC, dannypsnl requested changes

2023-08-17 22:01 UTC, dannypsnl commented on data_first_and_data_last.md
> +- `greaterThanEqual`
建議補上 `<=` 之類的符號輔助理解

2023-08-18 09:45 UTC, dannypsnl approved these changes

2023-08-18 12:12 UTC, merged