pure function 初稿
FizzyElt/functional-programming pull request #23
Opened 2023-08-25 18:46 UTC by FizzyElt

先寫一些，邊改邊補

2023-08-26 02:31 UTC, dannypsnl requested changes

2023-08-26 02:31 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
不，沒辦法
要考慮 partial function

2023-08-26 02:31 UTC, dannypsnl commented on pure_function.md
> +```
這個案例只是轉發，幾乎沒有描述任何事

2023-08-26 02:31 UTC, dannypsnl commented on pure_function.md
> +```
Same

2023-08-26 02:31 UTC, dannypsnl commented on pure_function.md
> +集合元素的對應又分三種類型，包含 **單射 (injection)**、**滿射 (surjection)**、**對射 (bijection)**。
「函數分為三種」

2023-08-26 06:57 UTC, dannypsnl commented on pure_function.md
> +```
Consider _Is length of string even?_

```hs
length :: String -> Int
is_even :: Int -> Bool
```

2023-08-26 07:44 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
e.g.
```hs
foo x =
  if x = 0
    then True
    else foo x
```

There has no definition when `x <> 0`

https://person.dibris.unige.it/moggi-eugenio/ftp/JSL-1984.pdf

2023-08-26 16:08 UTC, FizzyElt commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
所以這裡應該用 total function 應該更精確？

2023-08-26 16:15 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
是

2023-08-26 16:18 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
其實主要的問題就在「簡單的將集合慨念對應到程式的型別」這句話上，其實集合約束的不夠力，語義上不好用，因此函數也只是其中一個不好的模型

更合適的定義是 cpo (complete partial order) 跟連續函數

2023-08-26 16:18 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
如果目標是簡易的模型，就先提到函數的範圍很可能超過程式裡面的「函數」

2023-08-27 13:13 UTC, FizzyElt commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
這裡的範圍指的是哪些

2023-08-27 13:14 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
集合 $\mathbb{N}^\mathbb{N}$ 的基數

2023-08-27 13:14 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
就是變化版的 Turing theorem

2023-08-27 14:41 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
因為語言是有限構造的，至多可以表現可數多個 $\mathbb{N} \to \mathbb{N}$ 函數

2023-08-28 16:05 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
**可數多個**

$\mathbb{N}^\mathbb{N} = \mathbb{N} \to \mathbb{N}$

2023-09-12 12:08 UTC, dannypsnl commented on pure_function.md
> +在數學中，函數是一個集合 (稱為**定義域 domain**) 到另一個集合 (稱為**值域 codomain**) 的映射，假設我們有個函數 $f : A \to B$ ，則 $A$ (domain) 中每個元素都必須對應到 $B$ (codomain) 中的一個元素，在這裡我們可以簡單的將集合慨念對應到程式的型別，建立一個函數就是在實做映射的細節。
另一個更簡單的方法是 system F 中可以定義出 $V \cong (V \to 2) \to 2$ ，這對應到集合論中等於在說冪集合總是小於集合，在集合論中不合理但是在 F 中合理

而 $2 = \forall X . X \to X \to X$

2023-09-18 16:01 UTC, dannypsnl approved these changes

2023-09-18 16:01 UTC, dannypsnl commented on pure_function.md
> +$$\forall b \in B,\ \exist a \in A,\ f(a) = b$$
<img width="919" alt="image" src="https://github.com/FizzyElt/functional-programming/assets/22004511/8fe0a4f4-cb2f-400c-ac3a-1ef306e08973">

壞了，好像是多了一個 `\`

2023-09-18 16:01 UTC, dannypsnl commented
可以吧，我覺得剩下的可以移去 forester 那邊的實現再改

2023-09-19 14:40 UTC, FizzyElt commented
先合併，在從 forester 開新的

2023-09-19 14:40 UTC, merged