Pure function 文章遷移
FizzyElt/functional-programming pull request #31
Opened 2023-09-25 16:21 UTC by FizzyElt

2023-09-25 23:56 UTC, dannypsnl commented
程式小區塊是 `\code{...}`，大區塊是
```
\pre{\startverb%
...
\stopverb}
```

2023-09-26 00:25 UTC, dannypsnl requested changes

2023-09-26 00:25 UTC, dannypsnl commented on trees/fp-000J.tree
> +\p{在程式中你可以利用 function 做許多事情，不只是單純的運算，還包含了各種值的修改及各種非同步操作，雖然方便但也造成了閱讀及維護上的困難，而盡可能得撰寫 pure function 是一個可以有效減輕開發上的心智負擔，並且是使你能夠靈活組合函數的一個前提。}
> 維護上的困難，而盡可能得撰寫
維護上的困難。盡可能得撰寫

2023-09-26 00:25 UTC, dannypsnl commented on trees/fp-000J.tree
> +\transclude{fp-000N}
eof

2023-09-26 00:25 UTC, dannypsnl commented on trees/fp-000K.tree
> +\p{函數分三種類型，包含 \b{單射 (injection)}、\b{滿射 (surjection)}、\b{對射 (bijection)}。}
eof

2023-09-26 00:25 UTC, dannypsnl commented on trees/fp-000K.tree
> + 條件的函數總共有 #{|B|^{|A|}} 種，我們通常實現的都只會是其中幾種，而不是所有都實作。}
我們能實現的是有限的語法能實現的一小部分

2023-09-26 09:52 UTC, FizzyElt commented
> 程式小區塊是 `\code{...}`，大區塊是
> 
> ```
> \pre{\startverb%
> ...
> \stopverb}
> ```
我是指 
```haskell
is_even n =n `mod` 2 == 0
```
跟
```haskell
is_even n =mod n 2 == 0
``

2023-09-26 10:45 UTC, dannypsnl commented
喔喔，了解，我問一下 Jon

2023-09-26 10:51 UTC, dannypsnl commented
> 喔喔，了解，我問一下 Jon

Email list here: https://lists.sr.ht/~jonsterling/forester-discuss/%3CCADB3Nk%3D+r9Y8WNcppQZf8bKaqefJaNZAqYbQY_fn0se%3DELYLxg%40mail.gmail.com%3E

2023-09-27 03:41 UTC, dannypsnl approved these changes

2023-09-27 08:14 UTC, merged

2023-09-27 13:22 UTC, dannypsnl commented
@FizzyElt 用 forester 的 commit 992e8f6f646d18fb1e1ef8cb4762eb86dea5fa0b 就能用 ` 了