可預測與不可預測
FizzyElt/functional-programming pull request #37
Opened 2023-10-02 15:44 UTC by FizzyElt

2023-10-02 16:04 UTC, dannypsnl requested changes
這段感覺不是很必要，你是要講單元測試跟維護純函數嗎？
另外純函數本身就是偏向約束性定義，並不精確，我有點想移掉這整個 section

2023-10-02 17:19 UTC, FizzyElt commented
還是其實只要增加這兩個 section 就可以
- 透過單元測試難易度辨別函式純度
- 透過函式純度辨別單元測試難易度

2023-10-03 01:45 UTC, dannypsnl commented
第一個是可能的，比如說我們可以用模糊測試來找潛在的共用狀態之類的
但第二個方向應該沒啥用，畢竟一眼能看出純度就不用定義的那麼含糊了xd

2023-10-03 12:59 UTC, FizzyElt commented
目前暫定加上「透過單元測試難易度辨別函式純度」，該 section 關閉

2023-10-03 12:59 UTC, closed without merging