FP Functor and Category theory Functor
FizzyElt/functional-programming pull request #73
Opened 2023-10-24 15:37 UTC by FizzyElt

將原本 Lean 定義段落替換，並調整 Functor 內容順序

2023-10-24 18:04 UTC, dannypsnl requested changes

2023-10-24 18:04 UTC, dannypsnl commented on trees/fp-000H.tree
> +  (<$) :: a        -> f b -> f a
這個可以跟 lean 一樣移掉

2023-10-24 18:04 UTC, dannypsnl commented on trees/fp-000H.tree
> +\transclude{fp-000P}
EOF

2023-10-24 18:04 UTC, dannypsnl commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
也不是說必須檢查 laws，必須講清楚不滿足這寫約束就根本不是 functor，但語言裡面實際上定義的是上面講過的只帶入簽名的東西

如果要按照數學的慣例可以命名為 prefunctor

2023-10-25 02:24 UTC, FizzyElt commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
改成這樣？
「Functor class 的實例通過語言的檢查，都還不能視為範疇論中的 Functor，必須檢查 Functor laws 才會是範疇論中的 Functor。」

2023-10-25 02:25 UTC, FizzyElt commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
prefunctor 的 pre 是代表什麼

2023-10-25 02:38 UTC, dannypsnl commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
這時候用 pre 通常都是「準備是 xxx 但還不是 xxx」

2023-10-25 02:40 UTC, dannypsnl commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
「functor class 的實例不能視為範疇論中的 functor，必須檢查 functor 的約束才會是真正的 functor。」

2023-10-25 02:40 UTC, dannypsnl commented on trees/fp-000H.tree
> +  即便我們看了範疇論跟 FP 語言中的 Functor 定義，但在概念的銜接上仍然有困難，如果你看了 [Functor(functional programming) wiki](https://en.wikipedia.org/wiki/Functor_(functional_programming)) 會發現他是受範疇論啟發的 design pattern。而到底引用了哪些概念，以及與語言
我記得好像是 cat-0001

2023-10-25 02:44 UTC, dannypsnl commented
好像可以用 prefunctor 這個詞喔

<img width="567" alt="image" src="https://github.com/FizzyElt/functional-programming/assets/22004511/fffc1893-efd1-40e5-a072-f41430f74fec">

> from: https://www.isa-afp.org/browser_info/current/AFP/Category2/outline.pdf

2023-10-25 03:42 UTC, FizzyElt commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
我發現 Lean 有額外定義這個
https://leanprover-community.github.io/mathlib4_docs/Init/Control/Lawful.html#LawfulFunctor

2023-10-25 05:11 UTC, dannypsnl commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
那 Lean 就至少有正確的 categorical functor

2023-10-25 05:12 UTC, dannypsnl commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
另外要注意因為 Lean 有宇宙，所以 category 反倒是裡面的「小」結構，正是普通的 `Sort u`，這實際上也是 dependent type formalize category 的方案。其他語言也還是能塞進這些小東西裡面編碼跟做正確的 functor。

2023-10-25 05:13 UTC, dannypsnl commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
我是覺得正是用詞應該可以選 prefunctor，參照下面 Isabelle 對範疇論的形式化

2023-10-25 07:34 UTC, FizzyElt commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
感覺可以當額外補充

2023-10-25 08:26 UTC, dannypsnl commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
對，應該是開個 card 講這跟 F-alg 的關係

2023-10-25 08:27 UTC, dannypsnl commented on trees/fp-000P.tree
> +    Functor class 的實例通過語言的檢查，都被視為語言中的 Functor，然而因為不能施加限制的關係，這些實例並不總是範疇論中的 Functor，所以必須檢查 Functor laws 才會是範疇論中的 Functor。
因此提到 prefunctor 這個說法

2023-10-25 13:41 UTC, FizzyElt commented on trees/fp-000H.tree
> +  即便我們看了範疇論跟 FP 語言中的 Functor 定義，但在概念的銜接上仍然有困難，如果你看了 [Functor(functional programming) wiki](https://en.wikipedia.org/wiki/Functor_(functional_programming)) 會發現他是受範疇論啟發的 design pattern。而到底引用了哪些概念，以及與語言
這是在這裡加上 cat-0002 的連結嘛

2023-10-25 15:18 UTC, dannypsnl commented on trees/fp-000H.tree
> +  即便我們看了範疇論跟 FP 語言中的 Functor 定義，但在概念的銜接上仍然有困難，如果你看了 [Functor(functional programming) wiki](https://en.wikipedia.org/wiki/Functor_(functional_programming)) 會發現他是受範疇論啟發的 design pattern。而到底引用了哪些概念，以及與語言
沒錯

2023-10-25 16:08 UTC, dannypsnl requested changes

2023-10-25 16:08 UTC, dannypsnl commented on trees/fp-000P.tree
> +    Functor class 的實例不能視為範疇論中的 Functor，必須檢查 Functor 的約束才會是真正的 Functor。。
句號重複

2023-10-25 16:08 UTC, dannypsnl commented on trees/fp-000H.tree
> +\p{\b{Scala}}
可以用 block{…}{…} 語法

2023-10-25 16:08 UTC, dannypsnl commented on trees/fp-000H.tree
> +  如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，但現實我們幾乎不會想這樣做。所以這裡唯一的可能是指「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell w
我們常常這樣做，只是定義程式裡面的 functor 時不想弄得太複雜

2023-10-25 16:25 UTC, FizzyElt commented on trees/fp-000H.tree
> +  如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，但現實我們幾乎不會想這樣做。所以這裡唯一的可能是指「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell w
這裡是指哪部份的修正

2023-10-25 17:14 UTC, dannypsnl commented on trees/fp-000H.tree
> +  如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，但現實我們幾乎不會想這樣做。所以這裡唯一的可能是指「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell w
「現實我們幾乎不會想這樣做」這個聲明

2023-10-26 02:33 UTC, FizzyElt commented on trees/fp-000H.tree
> +  如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，但現實我們幾乎不會想這樣做。所以這裡唯一的可能是指「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell w
這樣接感覺與具有點不太通順，我想一下怎麼改

2023-10-26 02:37 UTC, FizzyElt commented on trees/fp-000H.tree
> +  如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，但現實我們幾乎不會想這樣做。所以這裡唯一的可能是指「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell w
如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，雖然我們常常這樣做，但是我們定義程式裡面的 Functor 時不想弄得太複雜。所以這裡指的都是「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell wiki](https://wiki.haskell.org/Typeclassopedia) 以及 fp-ts 作者所寫的 [Introduction to Functional Programming](https://github.com/enricopolanski/functional-programming#a-boundary-that-leads-to-functors) 中找到相關說明。

2023-10-26 02:38 UTC, FizzyElt commented on trees/fp-000H.tree
> +  如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，但現實我們幾乎不會想這樣做。所以這裡唯一的可能是指「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell w
常常這樣做，是思考方面還是實際方面？

2023-10-26 03:42 UTC, dannypsnl commented on trees/fp-000H.tree
> +  如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，但現實我們幾乎不會想這樣做。所以這裡唯一的可能是指「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell w
論文，應該算思考吧？另一個看法就是編譯器就算是這種應用，主要體現在我們證明 semantic preservation 的時候

2023-10-26 04:16 UTC, FizzyElt commented on trees/fp-000H.tree
> +  如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，但現實我們幾乎不會想這樣做。所以這裡唯一的可能是指「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell w
改成 常常這樣思考 好一些

2023-10-26 04:29 UTC, dannypsnl commented on trees/fp-000H.tree
> +  如果以「Functor 是兩個範疇之間的映射」這個觀點來看程式中的 Functor 似乎有些奇怪，通常我們看到的範例都是舉兩個不同範疇 #{C,D}，如果某一程式語言是一個範疇 #{C} 的話，那範疇 #{D} 就會是另一個語言，但現實我們幾乎不會想這樣做。所以這裡唯一的可能是指「 #{C} 與 #{C} 之間的映射」，也就是 \b{Endofunctor} 。你可以在 [Haskell w
恩應該可以

2023-10-26 07:53 UTC, dannypsnl approved these changes

2023-10-26 07:53 UTC, merged