F-algebra 翻譯
FizzyElt/functional-programming pull request #93
Opened 2023-11-27 14:00 UTC by FizzyElt

先給個初稿，有些名詞真不知道怎麼翻，可能翻的有點奇怪

2023-11-27 14:40 UTC, dannypsnl requested changes

2023-11-27 14:40 UTC, dannypsnl commented on trees/cat-0005.tree
> +\p{或者你可以將 Ring 寫成：}
應該可以用翻譯詞「環」

2023-11-27 14:40 UTC, dannypsnl commented on trees/cat-0005.tree
> +\p{下一步我們認定 #{m} 為範疇 #{C} 中的一個對象，這裡 #{C} 是一個 [cartesian closed category](cat-0004)。}
1. 要選一個足以表示簽名的範疇，這裡是 CCC
2. 「我們令 #{m} 是範疇 #{C} 中的一個 object」，這裡物件依然比對象是更好的翻譯，因為範疇論其實不太在乎 object，我們很容易發現 morphisms represent objects

2023-11-27 14:40 UTC, dannypsnl commented on trees/cat-0005.tree
> +\p{要理解 #{F}-algebra，我們需要一些觀察，第一個是我們可以用一組簽名來概括一個代數。例如，Monoid 有一組簽名：}
來表示一個代數

2023-11-27 14:40 UTC, dannypsnl commented on trees/cat-0005.tree
> +\p{現在我們概括了代數的定義。}
推廣

2023-11-27 14:40 UTC, dannypsnl commented on trees/cat-0006.tree
> +\p{在一個適當的範疇 #{C} 中，可以描述一個 #{F(-)} 符號，以及一個自函子 #{F:C \to C}，而 #{F}-algebra 為一個三元組：}
我們可以把簽名寫成 #{F(-)} 這個函子投射出的 #{F(m) \to m} 是 #{F}-algebra，可以記為三元組

2023-11-27 14:40 UTC, dannypsnl commented on trees/cat-0007.tree
> +\p{這些是跟範疇中初始對象 (initial object) 有關的一個定理}
這句話是在描述 Lambek's theorem，所以不應該在這張卡片，在本來的文章我也是寫在 parent card 裡面

2023-11-27 14:40 UTC, dannypsnl commented on trees/cat-000B.tree
> +\p{這篇主要從 Category Theory for Programmers 中學習 #{F}-algebra，並花了一些時間深思熟慮後用我們的方式表達其核心思想。這篇文章回答了一些問題，但我們總是有更多問題。什麼是單子（Monad）的代數？什麼是程式語言的代數（通常是有遞迴的語法樹）？希望你透過閱讀文章和練習也能很好地理解它。}
eof

2023-11-27 14:40 UTC, dannypsnl commented on trees/cat-000B.tree
> +\p{這篇主要從 Category Theory for Programmers 中學習 #{F}-algebra，並花了一些時間深思熟慮後用我們的方式表達其核心思想。這篇文章回答了一些問題，但我們總是有更多問題。什麼是單子（Monad）的代數？什麼是程式語言的代數（通常是有遞迴的語法樹）？希望你透過閱讀文章和練習也能很好地理解它。}
話說回來這段不能用吧，要改成能接到網站主軸裡面

2023-11-28 13:45 UTC, FizzyElt commented on trees/cat-0005.tree
> +\p{現在我們概括了代數的定義。}
這裡推廣的意思是什麼，是我們一般用推廣的意思嘛

2023-11-28 14:27 UTC, FizzyElt commented on trees/cat-0008.tree
> +\block{\strong{證明}}{
沒寫過，讓我研究一下

2023-11-28 14:28 UTC, FizzyElt commented on trees/cat-000B.tree
> +\p{這篇主要從 Category Theory for Programmers 中學習 #{F}-algebra，並花了一些時間深思熟慮後用我們的方式表達其核心思想。這篇文章回答了一些問題，但我們總是有更多問題。什麼是單子（Monad）的代數？什麼是程式語言的代數（通常是有遞迴的語法樹）？希望你透過閱讀文章和練習也能很好地理解它。}
我先移除，後續可意再補

2023-11-28 14:29 UTC, FizzyElt commented on trees/cat-0006.tree
> +\p{根據 #{F}-algebra 的定義，我們想知道固定 #{F} 形式的 #{F}-algebra 是否形成一個範疇，答案是肯定的。}
不確定你的意思，是直接寫這句話嘛

2023-11-28 14:53 UTC, dannypsnl commented on trees/cat-0005.tree
> +\p{現在我們概括了代數的定義。}
是指要修改成「現在我們推廣了代數的定義」
因為這裡代數不再只限於有「有意義」的簽名的那些傳統概念，而是直接變成某類 endofunctor 的產物

2023-11-28 15:17 UTC, dannypsnl requested changes

2023-11-28 15:17 UTC, dannypsnl commented on trees/cat-0007.tree
> +\p{一個同態為一個 #{C} 中的 #{m} 為一個使以下交換圖成立的態射。}
的態射 m

2023-11-28 15:17 UTC, dannypsnl commented on trees/cat-0006.tree
> +\p{在一個適當的範疇 #{C} 中，我們可以把簽名寫成 #{F(-)} 這個函子投射出的 #{F(m) \to m} 是 #{F}-algebra，可以記為三元組：}
這個函子前面要有逗號

2023-11-28 15:17 UTC, dannypsnl commented on trees/cat-0006.tree
> +\p{其中 #{\alpha : Fx \to x} 是 #{C} 中的一個態射。}
其實我正在好奇是不是翻譯成箭頭更好

2023-11-28 15:17 UTC, dannypsnl commented on trees/cat-0005.tree
> +\p{要理解 #{F}-algebra，我們需要一些觀察，第一個是我們可以用一組簽名來表示一個代數。例如，Monoid 有一組簽名：}
代數可以表示成一組簽名

2023-11-29 13:14 UTC, FizzyElt commented on trees/cat-0006.tree
> +\p{其中 #{\alpha : Fx \to x} 是 #{C} 中的一個態射。}
我個人認為態射讓人更好辨別，除非有什麼特殊狀況才翻箭頭

2023-11-29 22:03 UTC, dannypsnl requested changes

2023-11-29 22:03 UTC, dannypsnl commented on trees/cat-0007.tree
> +\p{我們可以額外檢查 identity 確實運作。}
*額外檢查我們可以發現 identity 也如預期運作

2023-11-29 22:03 UTC, dannypsnl commented on trees/cat-000A.tree
> +\p{作為一個對偶概念，我們可以畫出一個 coalgebra 的圖。}
+我們稱這種關係為 anamorphism

2023-11-29 22:03 UTC, dannypsnl commented on trees/cat-0009.tree
> +\p{一個常見的例子是 \code{foldr}，它是對 Catamorphism 的一種便利版本。}
它是~對~ Catamorphism 的一種便利版本

2023-11-29 22:03 UTC, dannypsnl commented on trees/cat-0009.tree
> +\p{一個常見的例子是 \code{foldr}，它是對 Catamorphism 的一種便利版本。}
*\code{foldr} 是一個常見的例子

2023-11-29 22:03 UTC, dannypsnl commented on trees/cat-0009.tree
> +\p{此理論實際上在證明初始代數 #{(F,i,j)} 的 #{C} 對象 #{i} 是 #{F} 的不動點。畫出 #{j} 的 inverse 可以得出下面交換圖}
*根據 Lambek's 理論可以畫出交換圖

2023-11-29 22:05 UTC, dannypsnl requested changes

2023-11-29 22:05 UTC, dannypsnl commented on trees/cat-0008.tree
> +\p{在一個初始代數（initial algebra） #{Fi \cong i}，#{(F,i,j)} 中的求值器 #{j} 是同構(isomorphism)。}
*初始代數是同構態射

2023-11-30 13:39 UTC, FizzyElt commented on trees/cat-0005.tree
> +\li{Monoid 是 #{C} 中的一個態射 #{1 + m \times m \to m}}
不太確定你的意思

2023-11-30 13:40 UTC, FizzyElt commented on trees/cat-0007.tree
> +    \li{態射皆為 #{(x,\alpha)\xrightarrow{Fm} (y,\beta)} 對象的同態，組合由函子定律給出。}
這個是要加在哪？

2023-11-30 13:46 UTC, dannypsnl commented on trees/cat-0008.tree
> +\p{因此 #{m} 是 #{j} 的 inverse，證明 #{j} 是同構。}
這裡論題是不是亂掉了？

2023-11-30 13:46 UTC, dannypsnl approved these changes

2023-11-30 13:49 UTC, FizzyElt commented on trees/cat-0008.tree
> +\p{因此 #{m} 是 #{j} 的 inverse，證明 #{j} 是同構。}
怎麼個亂掉法？

2023-11-30 15:30 UTC, merged